import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useAccount } from '../hooks/useAccount';
import { useEffect, useState } from 'react';
import { signAgreement, fetchSignatureRequests } from '../utils/actions';
import SignatureRequests from '../components/signatureRequests';

export default function Home() {
  const [signatures, setSignatures] = useState([]);
  const [isLoading, setIsLoading] = useState(true);
  const web3 = useAccount();

  useEffect(async () => {
    if (isLoading) {
      handleLoad()
    }
  }, [web3, isLoading]);

  async function handleLoad() {
    const signaturesFromChain = await fetchSignatureRequests(web3);
    if (signaturesFromChain !== 'error') {
      setSignatures(signaturesFromChain);
      setIsLoading(false);
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>HelloSign: Unchained</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          HelloSign: Unchained
        </h1>

        <p className={styles.description}>
          Smart eSignatures, powered by Ethereum
        </p>
        <a href='/create' style={{color: 'blue', marginBottom: '32px'}}>Create a request</a>
        <div className={styles.grid}>
          {signatures.length === 0 ? <h2>No requests.</h2> : <SignatureRequests signatureRequests={signatures} signAgreement={signAgreement} />}     
        </div>
      </main>

      <footer className={styles.footer}>
          <span><b>Address:</b> {web3?.account[0]}</span> <br />
          <span>Created by Justin Johnson, Akanksha Mehrotra, Kate Hueter, Ragav Khator, Andrew DaRe, Joanie Martinez and Ishmael Riles</span>
      </footer>
    </div>
  )
}
